Добавляет разметку главной страницы
htmlacademy-adaptive/1083949-cat-energy-25 pull request #2
Opened 2022-04-01 16:30 UTC by olgabelka81

2022-04-01 18:38 UTC, baileys-li requested changes
Молодцы, что не теряете время!
Тема БЭМа пока не освоена. Её и остальное можно обсудить на созвоне

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +    <link rel="stylesheet" href="../source/css/">
**Тут и далее**
Нет смысла выходить на папку выше и потом снова заходить в ту же папку где файл html. Стоит сразу писать пути относительно текущего файла

Тем более у вас по итогу курсе структура файлов в билде будет такой же как в папке `source`
```suggestion
    <link rel="icon" type="image/png" sizes="32x32" href="img/icon/favicon.png">
    <link rel="stylesheet" href="css/">
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +    <h1 class="visually hidden">CAT ENERGY</h1>
Наверное всё-таки
```suggestion
    <h1 class="visually-hidden">CAT ENERGY</h1>
```
Иначе это будет два разных класса

PS Ещё можно так 😈
```suggestion
    <h1 class="visuallyㅤhidden">CAT ENERGY</h1>
```
но на сдачу лучше так не делать, и вообще не делать

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +    <h1 class="visually hidden">CAT ENERGY</h1>
Поскольку весь сайт на русском, юзерам СР лучше явно обозначит, что контент на другом языке:
```suggestion
    <h1 class="visually-hidden" lang="en">CAT ENERGY</h1>
```
Или
```suggestion
    <h1 class="visually-hidden">Кэт Энерджи</h1>
```
Либо сделать `h1`  текст «<samp>Функциональное питание для котов</samp>» ниже

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +    <header class="main__header">
**Тут и далее**
Нет БЭМ класса блока, при том проблема явно системная

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        <img class="logo-main__img" width="101" height="18" alt="Логотип магазина" src="../source/img/icon/logo_main.svg">
Если есть текст на картинке, то его стоит зачитать
```suggestion
        <img class="logo-main__img" width="101" height="18" alt="Логотип «Кэт Энерджи»." src="img/icon/logo_main.svg">
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        <img class="logo-link__img" width="33" height="37" alt="Логотип с котом." src="../source/img/icon/logo_mobile.svg">
Не обязательно.
```suggestion
        <img class="logo-link__img" width="33" height="37" alt="Наш маскот." src="img/icon/logo_mobile.svg">
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +      </div>
1. Нет подписи
2. **По желанию** можно добавить aria атрибуты. В `aria-controls` пишется `id` элемента за отображение которого отвечает кнопка. 
3. Навигацию стоит обернуть в `nav`. 
4. Второй див внутри особо без надобности
5. Кнопка закрыть не нужно, потому что предполагается, что меняется кнопка открытия
```suggestion
      <button class="main-header__button-burger" type="button" aria-expanded="false" aria-controls="main-nav" >Открыть меню</button>
      <nav class="main-header__popover popover__menu" id="main-nav">
          <ul class="menu__content-list">
            <li class="menu__content-item">
              <a class="menu__content-link">Главная</a>
            </li>
            <li class="menu__content-item">
              <a class="menu__content-link" href="catalog.html">Каталог продукции</a>
            </li>
            <li class="menu__content-item">
              <a class="menu__content-link" href="form.html">Подбор программы</a>
            </li>
          </ul>
      </nav>
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        <a class="promo__link" href="#">Подобрать программу</a>
> [4.2.](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-2) Кнопка «Подобрать программу» должна вести на страницу формы для подбора программы.
```suggestion
        <a class="promo__link" href="form.html">Подобрать программу</a>
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +            <div class="promo__wrapper-link wrapper__link">
А зачем враппер?

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +              <a class="promo__link" href="#">Каталог slim</a>
Сделайте более осмысленный наполнитель
> [4.3.](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-4-3) В блоках «Похудение» и «Набор массы» ссылкой должна быть строка, начинающаяся со слова «Каталог». При нажатии должен осуществляться переход на соответствующие разделы каталога. Страницы разделов реализовывать не нужно.

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +          <ul class="advantages__list">
На других размерах есть номер, поэтому предположим что порядок важен
```suggestion
          <ol class="advantages__list">
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +          <dd class="example__list-definition">снижение веса</dd>
Скорее наоборот
```suggestion
          <dd class="example__list-definition">снижение веса</dd>
          <dt class="example__list-term">5 кг</dt>  
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        <a class="address__link" href="#">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</a>
Можно ссылку сразу засунуть
```suggestion
        <a class="address__link" href="https://goo.gl/maps/jXkocHRHetL6EzoB9">ул. Большая Конюшенная, д. 19/8 Санкт-Петербург</a>
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        <h2 class="address__title">Приглашаем к сотрудничеству дилеров!</h2>
**Не обязательно**. Просто альтернативный вариант
```suggestion
      <address class="section__address">
        <strong class="address__title">Приглашаем к сотрудничеству дилеров!</strong>
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +        </a>
1. Зачем две ссылки?
2. 
[3.8.](https://up.htmlacademy.ru/adaptive/25/project/cat-energy#cat-energy-3-8) Логотип и текст HTML Academy в футере являются ссылкой на [лендинг интенсива «HTML и CSS. Адаптивная вёрстка и автоматизация»](https://htmlacademy.ru/intensive/adaptive).

```suggestion
        <a class="footer__link-academy" href="https://htmlacademy.ru/intensive/adaptive">HTML Academy
          <svg class="link-academy__icon" width="27" height="34" fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 27 34">
            <path d="M13.64.02 13.5 0 0 1.4v24.61L13.5 34 27 26.01V1.41L13.64 0zm11.6 25L13.5 31.96 1.77 25V14.94l11.68 6.92.02 1.25-8.02-4.74v1.22l8.04 4.81.02 1.29-8.05-4.76v1.22l8.04 4.81 8.12-4.83V16.9l3.62-2.15v10.26zm0-11.57L22 15.33l-1.48.88-7.06-4.19-.01 1.22 6.04 3.58-.06.03-.13.07-.86.5-4.98-2.95-.01 1.22 3.93 2.33-.93.61-.02.01-2.97-1.74-.01 1.23 1.94 1.13-1.98 1.19L1.8 13.58l11.64-6.96 11.8 6.83zm0-1.22L13.43 5.3 1.77 12.22V2.99L13.5 1.76 25.23 3v9.24z" fill="#666"/>
          </svg>
        </a>
```

2022-04-01 18:38 UTC, baileys-li commented on source/index.html
> +      <a class="header__logo logo__link" href="#">
На главной лучше не куда не вести
```suggestion
      <a class="header__logo logo__link">
```

2022-04-02 06:33 UTC, olgabelka81 commented on source/index.html
> +      </div>
Не очень поняла: зачем эта подпись, что она даёт...

2022-04-02 06:36 UTC, olgabelka81 commented on source/index.html
> +            <div class="promo__wrapper-link wrapper__link">
Думала, чтоб добавить потом блоку border-top и не увеличивать кликабельность ссылки...

2022-04-02 17:51 UTC, merged